// ── City Travel Apps & Transport Guide ──────────────────────────────────────
// Referenced in planner.js as CITY_TRAVEL_APPS[cityId]
// maps[].star = true  → recommended first choice
// transit.card        → physical card/pass to get
// ride[].star = true  → use this, not street hailing
const CITY_TRAVEL_APPS = {
  nyc: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best real-time MTA subway & bus tracker', star: true },
      { n: 'Google Maps', note: 'Great for walking & driving' },
      { n: 'Waze', note: 'Best if you\'re driving' },
    ],
    transit: { card: 'OMNY (tap contactless card/phone)', apps: ['MTA App', 'Citymapper'], tip: 'Tap your bank card or phone directly — no MetroCard needed. Daily cap protects against overpaying.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft', note: 'Slightly cheaper off-peak' }],
    food: [{ n: 'Resy', note: 'Best for NYC reservations' }, { n: 'OpenTable' }, { n: 'Uber Eats' }],
    pay: 'Tap-to-pay accepted almost everywhere. Apple Pay & Google Pay widely supported.',
    sim: 'T-Mobile or AT&T prepaid SIM at any CVS, Walgreens, or airport.',
    tip: 'Subway beats taxis in Manhattan at all hours. Avoid yellow cabs for cross-borough trips.',
  },
  paris: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Best overall navigation', star: true },
      { n: 'RATP', note: 'Official app — real-time Metro & RER alerts' },
      { n: 'Maps.me', note: 'Best offline — download before you go' },
    ],
    transit: { card: 'Navigo Découverte (€5 deposit)', apps: ['RATP', 'Google Maps'], tip: 'Load a weekly Navigo pass — unlimited Metro + RER + bus, much cheaper than individual tickets.' },
    ride: [{ n: 'Uber' }, { n: 'Bolt', note: 'Often 20–30% cheaper than Uber' }, { n: 'Free Now', note: 'Books licensed taxis' }],
    food: [{ n: 'TheFork', note: 'Dominant reservations app in France' }, { n: 'Deliveroo', note: 'Best Paris delivery' }],
    pay: 'Cards accepted widely. Carry €20–30 cash for boulangeries and small cafés.',
    sim: 'Free Mobile or Orange visitor SIM at any tabac — cheap and fast data.',
    tip: 'Validate your ticket EVERY time you board — inspectors fine on the spot even with a valid pass.',
  },
  tokyo: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Excellent transit routing for Tokyo', star: true },
      { n: 'Navitime Japan', note: 'Best for complex rail + shinkansen routing' },
      { n: 'Hyperdia', note: 'Train-only planner with exact fares' },
    ],
    transit: { card: 'Suica IC card (add to Apple/Google Pay)', apps: ['Navitime', 'Google Maps'], tip: 'Add Suica to Apple/Google Pay before you land — tap on every gate and at convenience stores.' },
    ride: [{ n: 'GO (タクシーGO)', note: 'Best Japanese taxi app — metered, reliable', star: true }, { n: 'Uber', note: 'Available but limited and often pricier' }],
    food: [{ n: 'Tabelog', note: 'Japanese ratings bible' }, { n: 'Gurunavi', note: 'English-friendly restaurant finder' }, { n: 'HotPepper', note: 'Reservations & coupons' }],
    pay: 'CASH IS ESSENTIAL — many restaurants are cash-only. Suica works at all convenience stores. 7-Eleven and Japan Post ATMs always accept foreign cards.',
    sim: 'Pocket WiFi or IIJmio/Docomo data SIM at airport vending machines. eSIM options available online before departure.',
    tip: 'Google Maps works exceptionally well in Tokyo. Never flag a taxi without an app — use GO for reliable metered fares.',
  },
  bali: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works well for roads & popular spots', star: true },
      { n: 'Maps.me', note: 'Essential offline — some areas have no signal' },
    ],
    transit: { card: 'None (no public transit)', apps: ['Gojek', 'Grab'], tip: 'Rent a scooter ($5–8/day) or hire a private driver ($35–50/day) for total freedom. Far better value than ride-hailing everywhere.' },
    ride: [{ n: 'Gojek', note: 'Local super-app — cheaper and more coverage', star: true }, { n: 'Grab', note: 'Banned for pickup in Kuta/Seminyak — order to a meeting point' }],
    food: [{ n: 'GoFood (via Gojek)', note: 'Best food delivery across the island' }, { n: 'GrabFood' }],
    pay: 'Cash (IDR) is king for warungs, markets, and local businesses. ATMs widely available — withdraw large amounts to reduce fees.',
    sim: 'Telkomsel or XL Axiata SIMs at the airport — $5–10 for 30 days of fast data.',
    tip: 'Blue Bird taxis (blue, metered) are the safe choice in Kuta/Seminyak where ride apps are restricted. Avoid unmarked taxis.',
  },
  barcelona: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Best overall for Barcelona', star: true },
      { n: 'TMB App', note: 'Official Metro & bus — next-train timings' },
      { n: 'Citymapper', note: 'Good real-time transit alternative' },
    ],
    transit: { card: 'T-Casual (10 trips, ~€12)', apps: ['TMB App', 'Google Maps'], tip: 'T-Casual covers Metro, bus, and some trams. Buy at any Metro station — much cheaper than single tickets.' },
    ride: [{ n: 'Uber' }, { n: 'Bolt', note: 'Often cheaper, reliable coverage' }, { n: 'Cabify', note: 'Popular local alternative' }],
    food: [{ n: 'TheFork / ElTenedor', note: 'Dominant in Spain — often has discounts' }, { n: 'Glovo', note: 'Top delivery app in Spain' }],
    pay: 'Cards widely accepted. Carry €10–20 cash for La Boqueria and street tapas bars.',
    sim: 'Vodafone, Orange, or Movistar tourist SIMs at the airport — affordable EU roaming.',
    tip: 'Pickpocketing is common on La Rambla and the Metro. Use a crossbody bag and keep phones in front pockets.',
  },
  miami: {
    bestMap: 'Waze',
    maps: [
      { n: 'Waze', note: 'Essential for Miami traffic & I-95 alerts', star: true },
      { n: 'Google Maps', note: 'Good for transit routing and walking' },
    ],
    transit: { card: 'EASY Card', apps: ['Miami-Dade Transit'], tip: 'Miami is car-dependent. Metrorail is useful for the Brickell/Downtown corridor only.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Freebee', note: 'Free electric vehicles in South Beach & Wynwood' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Trendy South Beach & Wynwood spots' }, { n: 'Uber Eats' }],
    pay: 'Cards accepted everywhere.',
    sim: 'T-Mobile or AT&T prepaid at any Walmart, CVS, or airport.',
    tip: 'Rent a car for anything outside South Beach/Brickell. Traffic on I-95 is brutal 7–9 AM and 4–7 PM.',
  },
  hawaii: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works well on all islands', star: true },
      { n: 'Apple Maps', note: 'Excellent satellite view for trails & coastline' },
    ],
    transit: { card: 'Holo Card (Oahu only)', apps: ['DaBus2 (Oahu)'], tip: 'A rental car is essential on Maui, Big Island, and Kauai. TheBus on Oahu is affordable but slow.' },
    ride: [{ n: 'Uber', note: 'Oahu only' }, { n: 'Lyft', note: 'Oahu only' }],
    food: [{ n: 'OpenTable' }, { n: 'Yelp', note: 'Great for local plate lunch spots' }],
    pay: 'Cards accepted everywhere on the islands.',
    sim: 'T-Mobile, AT&T, and Verizon all have strong coverage on Oahu. Spotty on rural Big Island roads.',
    tip: 'Book rental cars and popular restaurants (like Mama\'s Fish House) weeks in advance — they sell out fast.',
  },
  losangeles: {
    bestMap: 'Waze',
    maps: [
      { n: 'Waze', note: 'Essential for LA traffic — use every time you drive', star: true },
      { n: 'Google Maps', note: 'Good for Metro routing' },
    ],
    transit: { card: 'TAP Card (Metro)', apps: ['Metro LA'], tip: 'LA is a car city. Metro covers downtown corridors but most attractions require driving or ride-hailing.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Bird / Lime', note: 'E-scooters in Venice, Santa Monica & DTLA' }],
    food: [{ n: 'Resy', note: 'Hot LA restaurant bookings' }, { n: 'OpenTable' }, { n: 'DoorDash', note: 'Top delivery app in California' }],
    pay: 'Cards everywhere. Valet parking is common — bring $5–10 cash for tips.',
    sim: 'T-Mobile or AT&T prepaid at any Target or Best Buy.',
    tip: 'Always budget 30–60 extra minutes when driving anywhere in LA. Waze is not optional.',
  },
  chicago: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for CTA "L" train real-time tracking', star: true },
      { n: 'Google Maps', note: 'Great for walking — Chicago is very walkable' },
    ],
    transit: { card: 'Ventra Card', apps: ['Ventra App', 'Citymapper'], tip: 'Load Ventra on your phone for NFC tap-in. The L train covers most tourist areas — much faster than taxis downtown.' },
    ride: [{ n: 'Uber', note: 'Reliable, especially from Midway/O\'Hare' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy' }, { n: 'Grubhub', note: 'Born in Chicago — best coverage' }],
    pay: 'Cards everywhere. Ventra card for transit.',
    sim: 'T-Mobile or AT&T prepaid at any CVS or Walgreens.',
    tip: 'Lake Shore Drive becomes a wind tunnel in winter. Use the L whenever possible — it\'s fast and avoids traffic entirely.',
  },
  lasvegas: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Best for the Strip — most things are walkable', star: true },
      { n: 'Waze', note: 'Use only if driving off-Strip' },
    ],
    transit: { card: 'None needed', apps: ['Las Vegas Monorail'], tip: 'The Strip is walkable between most casinos. The Deuce bus runs 24/7 on Las Vegas Blvd — $8 for a 24-hr pass.' },
    ride: [{ n: 'Uber', note: 'Designated pickup spots at all major casinos' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable', note: 'Book celebrity chef restaurants months ahead' }, { n: 'Resy' }],
    pay: 'Cards everywhere including casino floors. ATM fees inside casinos are very high — use your hotel ATM.',
    sim: 'T-Mobile or AT&T. Signal can be weak inside large casinos.',
    tip: 'Walking the Strip takes much longer than it looks — casinos are enormous. Allocate 20+ minutes per casino transfer on foot.',
  },
  neworleans: {
    bestMap: 'Google Maps',
    maps: [{ n: 'Google Maps', note: 'Works well in the French Quarter', star: true }],
    transit: { card: 'Jazzy Pass', apps: ['RTA New Orleans'], tip: 'The St. Charles Streetcar is scenic and functional. The French Quarter is very walkable.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable', note: 'Reserve top Creole restaurants 2+ weeks ahead' }, { n: 'Yelp', note: 'Good for discovering local spots' }],
    pay: 'Carry cash for jazz clubs, second lines, and street food. Cards at restaurants.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Book Antoine\'s, Commander\'s Palace, and landmark restaurants at least 2 weeks out.',
  },
  nashville: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', star: true },
      { n: 'Waze', note: 'Helpful on I-40 and I-65' },
    ],
    transit: { card: 'None', apps: ['WeGo Nashville'], tip: 'Nashville is very car-centric. Broadway and the Gulch are walkable — everywhere else needs a ride.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Bird / Lime', note: 'E-scooters everywhere downtown' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'New and trendy spots' }],
    pay: 'Cards everywhere. Cash for honky-tonk cover charges and tip jars.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Hot chicken spots (Prince\'s, Hattie B\'s) have long queues at peak hours. Go early or late.',
  },
  sanfrancisco: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for Muni, BART, and cable car routing', star: true },
      { n: 'Google Maps', note: 'Good overall' },
    ],
    transit: { card: 'Clipper Card (tap-to-pay)', apps: ['Muni Mobile', 'BART App'], tip: 'BART connects SFO to downtown in 30 minutes. Clipper covers BART, Muni, and ferry — load on Apple/Google Pay.' },
    ride: [{ n: 'Uber', note: 'Founded here — very reliable' }, { n: 'Lyft', note: 'Also founded in SF' }, { n: 'Lime / Bird', note: 'E-scooters in SoMa, Mission & Marina' }],
    food: [{ n: 'Resy', note: 'SF\'s top restaurant booking app' }, { n: 'OpenTable' }, { n: 'DoorDash', note: 'Founded in SF — fast delivery' }],
    pay: 'Very cashless. Tap-to-pay everywhere. Some Mission taquerías are cash-only.',
    sim: 'T-Mobile or AT&T. Signal can drop in Muni tunnels.',
    tip: 'Fog is heaviest in the morning — especially in the Sunset district. The Embarcadero and Mission are typically fog-free.',
  },
  orlando: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Good for resort area navigation', star: true },
      { n: 'My Disney Experience', note: 'ESSENTIAL if visiting Disney — live wait times & dining' },
      { n: 'Universal Orlando', note: 'Live wait times and Express Pass management' },
    ],
    transit: { card: 'None needed for parks', apps: ['My Disney Experience', 'Lyft'], tip: 'Disney\'s internal buses and monorail are free between all Disney hotels and parks. A car is needed for non-Disney attractions.' },
    ride: [{ n: 'Uber', note: 'Most reliable for airport transfers' }, { n: 'Lyft' }, { n: 'Mears Connect', note: 'Shuttle from MCO — affordable but slower' }],
    food: [{ n: 'My Disney Experience', note: 'Book Disney dining 60 days out — essential' }, { n: 'OpenTable', note: 'For restaurants outside parks' }],
    pay: 'Disney MagicBand links to your card for cashless payments inside parks.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Book Disney dining reservations exactly 60 days before arrival. Popular spots like Be Our Guest book out in minutes.',
  },
  austin: {
    bestMap: 'Waze',
    maps: [
      { n: 'Waze', note: 'Essential for Austin traffic on I-35', star: true },
      { n: 'Google Maps', note: 'Good for downtown navigation' },
    ],
    transit: { card: 'None (car-dependent)', apps: ['CapMetro'], tip: 'Downtown and 6th Street are walkable. Everything else requires a car or ride.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Bird / Lime', note: 'Scooters around 6th St and UT campus' }],
    food: [{ n: 'Resy', note: 'Austin\'s hot restaurant booking app' }, { n: 'OpenTable' }, { n: 'DoorDash' }],
    pay: 'Cards everywhere. Cash for food trucks.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Franklin Barbecue queues start at 7 AM for 11 AM opening. Pre-order online to skip the line.',
  },
  seattle: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Excellent — great transit integration', star: true },
      { n: 'OneBusAway', note: 'Best real-time King County Metro tracking' },
    ],
    transit: { card: 'ORCA Card (tap-to-pay)', apps: ['Transit App', 'OneBusAway'], tip: 'Light Rail connects SeaTac to Capitol Hill and downtown. ORCA covers Link, bus, and Sounder — load via the ORCA app.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Lime', note: 'E-bikes and scooters citywide' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Trendy Capitol Hill & SLU spots' }, { n: 'DoorDash' }],
    pay: 'Very cashless. Tap-to-pay everywhere.',
    sim: 'T-Mobile (HQ is in Bellevue) — best coverage and value in the Pacific Northwest.',
    tip: 'Pike Place Market is best before 10 AM. A packable rain jacket is essential year-round.',
  },
  london: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Gold standard for London transit — use this', star: true },
      { n: 'TfL Go', note: 'Official TfL app — real-time disruption alerts' },
      { n: 'Google Maps', note: 'Good for walking and transit times' },
    ],
    transit: { card: 'Contactless bank card or phone (no Oyster card needed)', apps: ['Citymapper', 'TfL Go'], tip: 'Tap your contactless card or phone on every yellow reader. Daily & weekly fare caps apply automatically — cheaper than Oyster in most cases.' },
    ride: [{ n: 'Uber' }, { n: 'Bolt', note: 'Often 20–30% cheaper than Uber' }, { n: 'Gett', note: 'Books licensed black cabs at metered rate' }],
    food: [{ n: 'Resy', note: 'Top London restaurant booking app' }, { n: 'OpenTable' }, { n: 'Deliveroo', note: 'Best delivery coverage in London' }],
    pay: 'London is highly cashless — tap everywhere. Some markets and older pubs prefer cash.',
    sim: 'Three, EE, or giffgaff SIM at any Tesco or supermarket — £10 for 30 days with generous data.',
    tip: 'Oyster cards are being phased out. Use your bank contactless or Apple/Google Pay — automatic daily capping makes it very cost-effective.',
  },
  rome: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works well and has good offline option', star: true },
      { n: 'Maps.me', note: 'Best offline map — download before leaving wifi' },
      { n: 'ATAC Roma', note: 'Official Rome transit app for bus & tram times' },
    ],
    transit: { card: 'Roma Pass (includes transit)', apps: ['ATAC Roma', 'Google Maps'], tip: 'ALWAYS validate your ticket before boarding — inspectors fine tourists heavily. The Metro is limited to 2 lines; buses and walking are often faster.' },
    ride: [{ n: 'Free Now', note: 'Books licensed white taxis — safest option', star: true }, { n: 'Uber', note: 'Only Uber Black/Van available in Italy — expensive' }],
    food: [{ n: 'TheFork', note: 'Popular reservations app in Italy' }, { n: 'Tripadvisor', note: 'Good for filtering tourist-trap restaurants' }],
    pay: 'Many small trattorias are cash-preferred or cash-only. Carry €30–50 at all times.',
    sim: 'TIM, Vodafone, or Wind Tre tourist SIMs at Termini station or any tobacco shop.',
    tip: 'Book Vatican and Colosseum skip-the-line tickets 2–3 weeks ahead online. Queue times without tickets can exceed 3 hours.',
  },
  amsterdam: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Excellent transit integration', star: true },
      { n: '9292', note: 'Best Dutch public transit planner — accurate nationwide' },
      { n: 'GVB App', note: 'City tram, metro & bus live departures' },
    ],
    transit: { card: 'OV-chipkaart or tap contactless', apps: ['9292', 'GVB App'], tip: 'Tap IN and OUT on every vehicle — not tapping out charges the maximum fare. Contactless bank cards now work on most GVB services.' },
    ride: [{ n: 'Uber' }, { n: 'Bolt', note: 'Popular and cheaper' }],
    food: [{ n: 'OpenTable' }, { n: 'Deliveroo' }, { n: 'Thuisbezorgd', note: 'Local Dutch delivery app' }],
    pay: 'Very cashless — but Dutch PIN (debit) is preferred over Visa/Mastercard at some local shops. Notify your bank before traveling.',
    sim: 'Lebara or KPN SIM at Albert Heijn supermarket — affordable with good coverage.',
    tip: 'Rent a bike on day 1 — fastest, cheapest, and most local way to see the city. Watch for tram tracks when cycling.',
  },
  sydney: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Excellent for Sydney transit + Opal integration', star: true },
      { n: 'Transport NSW', note: 'Official app — real-time trains, buses & ferries' },
      { n: 'Apple Maps', note: 'Also excellent in Australia' },
    ],
    transit: { card: 'Opal Card or contactless tap', apps: ['Transport NSW', 'Google Maps'], tip: 'Tap on AND off every trip — fares are distance-based. Daily and weekly caps protect against overpaying.' },
    ride: [{ n: 'Uber' }, { n: 'DiDi', note: 'Usually 15–20% cheaper than Uber' }, { n: 'Ola', note: 'Competitive option' }],
    food: [{ n: 'OpenTable' }, { n: 'Uber Eats' }, { n: 'Menulog', note: 'Popular local delivery app' }],
    pay: 'Australia is extremely cashless — tap everywhere. "Card only" signs are common even at market stalls.',
    sim: 'Optus or Telstra tourist SIM at any 7-Eleven or airport — 28-day prepaid plans with generous data.',
    tip: 'Take the Manly Ferry from Circular Quay — one of the best city views in the world for just a regular Opal tap.',
  },
  dubai: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works very well in Dubai', star: true },
      { n: 'Waze', note: 'Good for Sheikh Zayed Road traffic' },
      { n: 'RTA Dubai', note: 'Official app for Metro, bus & Dubai Ferry' },
    ],
    transit: { card: 'Nol Card (Metro + bus + water taxi)', apps: ['RTA Dubai', 'Google Maps'], tip: 'The Metro Red Line covers Marina to Downtown to Airport — fast and air-conditioned. Get a Nol Silver Card at any station.' },
    ride: [{ n: 'Uber' }, { n: 'Careem', note: 'Regional super-app — often cheaper, loyalty rewards' }],
    food: [{ n: 'Talabat', note: 'Dominant food delivery in the UAE' }, { n: 'Deliveroo' }, { n: 'Careem Now' }],
    pay: 'Cards accepted everywhere — one of the most cashless cities in the world. Keep some AED for taxis and souks.',
    sim: 'Du or Etisalat tourist SIM at the airport (passport required) — fast 5G coverage across the city.',
    tip: 'Dress modestly when visiting malls, mosques, and markets. The Metro\'s Women & Children car is the first carriage.',
  },
  bangkok: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works well for Bangkok transit routing', star: true },
      { n: 'Maps.me', note: 'Good offline backup — download city before leaving wifi' },
    ],
    transit: { card: 'Rabbit Card (BTS) + MRT card', apps: ['Google Maps', 'Grab'], tip: 'BTS SkyTrain and MRT Metro are fast and air-conditioned — use them to skip Bangkok\'s notorious traffic. Rabbit card reloadable at any BTS station.' },
    ride: [{ n: 'Grab', note: 'ESSENTIAL — safer and fairer than street taxis. Always use Grab.', star: true }, { n: 'Bolt', note: 'Growing in Bangkok — competitive on price' }],
    food: [{ n: 'GrabFood', note: 'Fast and widely available' }, { n: 'LINE MAN', note: 'Very popular locally — great for street-food style restaurants' }, { n: 'Foodpanda' }],
    pay: 'Cash (Thai Baht) essential for street food, markets, and tuk-tuks. Cards at malls and hotels.',
    sim: 'AIS or DTAC tourist SIM at the airport — $10–15 for 30 days of fast data.',
    tip: 'Always use Grab instead of flagging a street taxi. Unmetered taxis can quote 5–10× the fair price for tourists.',
  },
  singapore: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for Singapore MRT + bus routing', star: true },
      { n: 'Google Maps', note: 'Also excellent — very accurate for Singapore' },
      { n: 'MyTransport.SG', note: 'Official app with real-time bus arrival times' },
    ],
    transit: { card: 'EZ-Link or SimplyGo (tap contactless)', apps: ['Citymapper', 'MyTransport.SG'], tip: 'Singapore\'s MRT is world-class — clean, punctual, air-conditioned. SimplyGo lets you tap with your contactless bank card. Tap in AND out.' },
    ride: [{ n: 'Grab', note: 'Dominant ride-hailing in Singapore', star: true }, { n: 'Gojek' }, { n: 'ComfortDelGro', note: 'Official taxi app — metered and reliable' }],
    food: [{ n: 'GrabFood' }, { n: 'Foodpanda', note: 'Wide hawker & restaurant coverage' }, { n: 'Deliveroo', note: 'Good for higher-end restaurants' }],
    pay: 'Extremely cashless — PayNow, NETS, cards, and Apple/Google Pay everywhere. Some older hawker stalls are cash-only.',
    sim: 'Changi Airport has excellent free WiFi. Singtel or Starhub tourist SIMs at airport convenience stores for great data.',
    tip: 'Hawker centres are the best food experience and extremely affordable ($3–6 per dish). Google Maps has good hawker stall ratings.',
  },
  lisbon: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Great for Lisbon transit and navigation', star: true },
      { n: 'Carris Metropolitana', note: 'Official tram, bus & metro app' },
    ],
    transit: { card: 'Viva Viagem card (€0.50)', apps: ['Carris', 'Google Maps'], tip: 'Load 24-hour zapping credit on the Viva Viagem card for Metro, tram, and bus. Tram 28 is iconic but crowded — try early morning.' },
    ride: [{ n: 'Uber' }, { n: 'Bolt', note: 'Very popular in Lisbon — usually 20% cheaper than Uber' }, { n: 'Free Now', note: 'Books licensed taxis' }],
    food: [{ n: 'TheFork', note: 'Popular restaurant reservations across Portugal' }, { n: 'Uber Eats' }, { n: 'Glovo', note: 'Popular local delivery' }],
    pay: 'Cards widely accepted. Carry €10–20 cash for pastelarias and local tabacs.',
    sim: 'NOS, MEO, or Vodafone PT SIM at Lisbon Airport — affordable EU data packages.',
    tip: 'Lisbon\'s hills are steep — wear comfortable shoes. The Metro is much faster than the historic trams.',
  },
  seoul: {
    bestMap: 'Naver Map',
    maps: [
      { n: 'Naver Map', note: 'ESSENTIAL — Google Maps is unreliable in South Korea', star: true },
      { n: 'KakaoMap', note: 'Excellent alternative — also very accurate' },
      { n: 'Kakao Metro', note: 'Best for Seoul subway with live info' },
    ],
    transit: { card: 'T-money card (tap everywhere)', apps: ['Kakao Metro', 'Naver Map'], tip: 'T-money works on subway, bus, and some taxis. Seoul\'s subway is one of the world\'s best — fast, clean, Wi-Fi equipped, and cheap (~$1/trip).' },
    ride: [{ n: 'KakaoTaxi', note: 'Dominant taxi app in Korea — always use this', star: true }, { n: 'Uber', note: 'Very limited in Seoul — stick to KakaoTaxi' }],
    food: [{ n: 'Baemin (배달의민족)', note: 'Korea\'s #1 food delivery app' }, { n: 'Coupang Eats', note: 'Fast delivery, often with discounts' }, { n: 'Naver Map', note: 'Use for restaurant ratings & reservations' }],
    pay: 'South Korea is extremely cashless — Samsung Pay, Kakao Pay, and cards everywhere. T-money for transit. Some pojangmacha (street stalls) are cash only.',
    sim: 'KT, SK Telecom, or LG U+ tourist SIMs at Incheon Airport — buy a T-money compatible data SIM.',
    tip: 'Google Maps gives wrong transit directions in Korea. Install Naver Map before you land — it is non-negotiable.',
  },
  mexicocity: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Works well for Mexico City', star: true },
      { n: 'Waze', note: 'Good for Periférico and highway traffic' },
      { n: 'Moovit', note: 'Useful for Metro and Metrobús routing' },
    ],
    transit: { card: 'CDMX Metro card (reloadable, ~$0.25/trip)', apps: ['CDMX App', 'Moovit'], tip: 'The Metro is extremely cheap and extensive. Gets very crowded at rush hour — take Uber/Cabify during peak times instead.' },
    ride: [{ n: 'Uber', note: 'Very popular and safe in CDMX — use over street taxis', star: true }, { n: 'Cabify' }, { n: 'DiDi', note: 'Often cheapest option' }],
    food: [{ n: 'Uber Eats' }, { n: 'Rappi', note: 'Very popular in LATAM — fast delivery' }, { n: 'DiDi Food', note: 'Good value' }],
    pay: 'Cash (MXN pesos) essential for street tacos, markets, and local restaurants. Cards at larger establishments.',
    sim: 'Telcel SIM at airport or any OXXO convenience store — best coverage nationwide.',
    tip: 'Only take Uber, Cabify, or DiDi — NEVER hail a random street taxi in CDMX. Book all rides via app for safety.',
  },
  sandiego: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', star: true },
      { n: 'Waze', note: 'Useful on I-5 and I-8' },
    ],
    transit: { card: 'Compass Card (MTS)', apps: ['MTS San Diego'], tip: 'The Trolley is useful for downtown and border crossing to Tijuana. San Diego is otherwise car-dependent.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable' }, { n: 'Yelp', note: 'Great for taco shop discovery' }, { n: 'DoorDash' }],
    pay: 'Cards accepted everywhere. Carry some USD cash for street tacos near the border.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Take the San Diego Trolley to the border and walk across to Tijuana — much easier than driving and parking.',
  },
  washingtondc: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for DC Metro + bus routing', star: true },
      { n: 'Google Maps', note: 'Great for walking between monuments' },
    ],
    transit: { card: 'SmarTrip Card (tap-to-pay)', apps: ['DC Metro', 'Citymapper'], tip: 'Avoid the Metro during rush hour (7–9 AM, 5–7 PM) — trains are severely overcrowded. Most Mall monuments are within walking distance of each other.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Capital Bikeshare', note: 'Great for the National Mall — all bike paths are flat' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Georgetown & H Street spots' }, { n: 'Uber Eats' }],
    pay: 'Cards everywhere. Many Smithsonian cafeterias are cashless.',
    sim: 'T-Mobile, AT&T, or Verizon — all strong in DC.',
    tip: 'All Smithsonian museums are free. Book timed entry online in advance for the most popular (Natural History, Air & Space).',
  },
  boston: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for MBTA "T" routing and real-time alerts', star: true },
      { n: 'Google Maps', note: 'Good for walking — Boston is very walkable' },
    ],
    transit: { card: 'CharlieCard or contactless tap', apps: ['MBTA', 'Citymapper'], tip: 'Boston is very walkable — the Freedom Trail connects most historic sites on foot. The T covers the rest. Park Street is the central hub.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Trendy Back Bay & South End spots' }, { n: 'Grubhub', note: 'Strong Boston delivery' }],
    pay: 'Cards accepted everywhere. Tap contactless on the T\'s new fare gates.',
    sim: 'T-Mobile, AT&T, or Verizon.',
    tip: 'Driving in Boston is notoriously difficult. The T is faster and much less stressful for most destinations.',
  },
  denver: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', star: true },
      { n: 'Waze', note: 'Useful on I-25 and I-70 to the mountains' },
    ],
    transit: { card: 'myRide (RTD)', apps: ['RTD Denver'], tip: 'The A-Line light rail connects Denver Airport to Union Station in 37 minutes — much faster than driving. The 16th Street Mall Free MallRide bus is handy downtown.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Lime', note: 'E-scooters widely available downtown' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'RiNo and LoHi restaurant bookings' }, { n: 'DoorDash' }],
    pay: 'Cards everywhere.',
    sim: 'T-Mobile for city; Verizon best for mountain/rural areas.',
    tip: 'Altitude sickness is real at 5,280 ft. Drink extra water your first day and avoid alcohol until acclimatized.',
  },
  portland: {
    bestMap: 'Google Maps',
    maps: [
      { n: 'Google Maps', note: 'Excellent for Portland transit', star: true },
      { n: 'Transit App', note: 'Real-time TriMet tracking' },
    ],
    transit: { card: 'Hop Fastpass (tap-to-pay)', apps: ['TriMet', 'Transit App'], tip: 'Portland has one of the best US transit systems — MAX light rail, streetcar, and buses on one Hop card. Downtown has a free fare zone on the MAX.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }, { n: 'Lime / Bird', note: 'E-bikes popular for crossing the bridges' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Trendy NE and SE Portland spots' }, { n: 'DoorDash' }],
    pay: 'Very cashless. Many Portland restaurants are card-only.',
    sim: 'T-Mobile has strong Pacific Northwest coverage.',
    tip: 'Portland\'s food cart pods (Mississippi Ave, SE Division) are a local institution — try multiple carts for a real Portland food experience.',
  },
  atlanta: {
    bestMap: 'Waze',
    maps: [
      { n: 'Waze', note: 'Essential — Atlanta has some of the worst US traffic congestion', star: true },
      { n: 'Google Maps', note: 'Use for MARTA routing and walking' },
    ],
    transit: { card: 'Breeze Card (MARTA)', apps: ['MARTA App'], tip: 'MARTA rail connects the airport directly to Midtown and Downtown. Atlanta is very car-dependent beyond these corridors.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Ponce City Market & Buckhead spots' }, { n: 'DoorDash' }],
    pay: 'Cards everywhere.',
    sim: 'T-Mobile or AT&T.',
    tip: 'Budget double the transit time if driving — Atlanta\'s I-285/I-75/I-85 interchange is genuinely brutal during rush hours.',
  },
  philadelphia: {
    bestMap: 'Citymapper',
    maps: [
      { n: 'Citymapper', note: 'Best for SEPTA real-time routing', star: true },
      { n: 'Google Maps', note: 'Great for walking — Center City is very walkable' },
    ],
    transit: { card: 'SEPTA Key Card (tap-to-pay)', apps: ['SEPTA', 'Citymapper'], tip: 'Center City Philadelphia is very walkable. SEPTA Market-Frankford Line and Broad Street Line cover most tourist areas.' },
    ride: [{ n: 'Uber' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable' }, { n: 'Resy', note: 'Rittenhouse & Fishtown trendy spots' }, { n: 'Grubhub' }],
    pay: 'Cards everywhere. Cash for Reading Terminal Market vendors.',
    sim: 'T-Mobile, AT&T, or Verizon.',
    tip: 'Reading Terminal Market is open until 6 PM most days — arrive before noon for the freshest selection at DiNic\'s and Beiler\'s Bakery.',
  },
  phoenix: {
    bestMap: 'Waze',
    maps: [
      { n: 'Waze', note: 'Essential for Phoenix freeways and traffic', star: true },
      { n: 'Google Maps', note: 'Good for general navigation' },
    ],
    transit: { card: 'Platinum Pass (Valley Metro)', apps: ['Valley Metro'], tip: 'Phoenix is one of the most car-dependent cities in the US. A rental car is essentially mandatory. Light rail useful for the ASU–Downtown–Tempe corridor only.' },
    ride: [{ n: 'Uber', note: 'Essential for airport transfers if not renting a car' }, { n: 'Lyft' }],
    food: [{ n: 'OpenTable', note: 'Good Scottsdale & Downtown selection' }, { n: 'DoorDash' }, { n: 'Uber Eats' }],
    pay: 'Cards everywhere.',
    sim: 'T-Mobile, AT&T, or Verizon.',
    tip: 'In summer (June–September), heat exceeds 110°F (43°C). Never walk long distances outdoors between 10 AM–6 PM. A car with AC is not optional.',
  },
};

// ── City Currency Data ────────────────────────────────────────────────────────
// code: ISO 4217 currency code (used with Frankfurter API)
// name: display name
// symbol: currency symbol
// usd cities get no rate fetch (already home currency)
const CITY_CURRENCY = {
  nyc:          { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  miami:        { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  hawaii:       { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  losangeles:   { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  chicago:      { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  lasvegas:     { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  neworleans:   { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  nashville:    { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  sanfrancisco: { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  orlando:      { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  austin:       { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  seattle:      { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  sandiego:     { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  washingtondc: { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  boston:       { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  denver:       { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  portland:     { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  atlanta:      { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  philadelphia: { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  phoenix:      { code: 'USD', name: 'US Dollar',          symbol: '$'   },
  paris:        { code: 'EUR', name: 'Euro',               symbol: '€'   },
  barcelona:    { code: 'EUR', name: 'Euro',               symbol: '€'   },
  rome:         { code: 'EUR', name: 'Euro',               symbol: '€'   },
  amsterdam:    { code: 'EUR', name: 'Euro',               symbol: '€'   },
  lisbon:       { code: 'EUR', name: 'Euro',               symbol: '€'   },
  london:       { code: 'GBP', name: 'British Pound',      symbol: '£'   },
  tokyo:        { code: 'JPY', name: 'Japanese Yen',       symbol: '¥'   },
  bali:         { code: 'IDR', name: 'Indonesian Rupiah',  symbol: 'Rp'  },
  sydney:       { code: 'AUD', name: 'Australian Dollar',  symbol: 'A$'  },
  dubai:        { code: 'AED', name: 'UAE Dirham',         symbol: 'AED' },
  bangkok:      { code: 'THB', name: 'Thai Baht',          symbol: '฿'   },
  singapore:    { code: 'SGD', name: 'Singapore Dollar',   symbol: 'S$'  },
  seoul:        { code: 'KRW', name: 'South Korean Won',   symbol: '₩'   },
  mexicocity:   { code: 'MXN', name: 'Mexican Peso',       symbol: 'MX$' },
};
